name: PR testing & preview

on:
  pull_request:

jobs:
  build_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Cache Composer dependencies
        uses: actions/cache@v2.1.4
        with:
          path: /tmp/composer-cache
          key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}

      - name: Install dependencies
        uses: php-actions/composer@v5
        with:
          dev: yes
          args: --ignore-platform-reqs
          
      - name: Copy .env
        run: cp .env.example .env
        
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_STRIPE_SECRET_KEY: ${{ secrets.STRIPE_PUBLIC_KEY }}
          envkey_STRIPE_PUBLIC_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
          file_name: .env

      - name: Run unit test
        run: |
          ./vendor/bin/phpunit tests/
